name: Auto Deploy

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main (sửa nếu cần)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Chạy trên máy chủ Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List directory
        run: ls -al /home/runner/work/TestThanhAuto/
      - name: Run build script
        run: ./TestThanhAuto/build.sh  # Kiểm tra xem file này có tồn tại không  
      - name: Debug working directory
        run: pwd && ls -al  
      - name: Install dependencies
        run: npm install
        working-directory: ./TestThanhAuto
              
          
